### ISSUE TITLE
Does not work with sirhurt or KRNL

### ISSUE THREAD

**Issue by jonahnm** [OpenGamerTips/Roblox-White#1]
(title) please help i added the header name for krnl and it returns fingerprint not supplied with running from krnl and same with sirhurt but it works perfectly fine for synapse X

**Comment by OpenGamerTips** [comment]
I'm redoing the whitelist right now because one of my friends wanted me to
remake it. This one is more secure and will be hard to crack.

>

**Comment by jonahnm** [comment]
> I'm redoing the whitelist right now because one of my friends wanted me to remake it. This one is more secure and will be hard to crack.
> […](#)

i fixed it by changing the method it gets the HWID but yeah ill still use the new ver
